//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemserk.Examples
{
    
    
    public enum DamageTypeAssetEnum
    {
        
        ElectricDamage = 1 << 0,
        
        FireDamage = 1 << 1,
        
        IceDamage = 1 << 2,
        
        PoisonDamage = 1 << 3,
    }
}
