//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemserk.Examples
{
    using System;
    
    [Flags()]
    public enum MovementTypeAssetEnum
    {
        AirMovement = 1 << 0,
        GroundMovement = 1 << 1,
        SpaceMovement = 1 << 2,
        VoidMovement = 1 << 3,
        WaterMovement = 1 << 4,
    }
}
