//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemserk.Examples
{
    
    
    public partial class BasicAttacks
    {
        
        public static int Attack1 = 1;
        
        public static int Attack2 = 2;
        
        public static int Attack3 = 4;
        
        public const int TOTAL_TYPES = 3;
        
        public static string ValueToName(int value)
        {
            if (value == Attack1) return nameof(Attack1);
            if (value == Attack2) return nameof(Attack2);
            if (value == Attack3) return nameof(Attack3);
            return null;
        }
        
        public static void GetNames(int mask, System.Collections.Generic.ICollection<string> collection)
        {
            if ((mask & (1 << Attack1)) == (1 << Attack1)) collection.Add(nameof(Attack1));
            if ((mask & (1 << Attack2)) == (1 << Attack2)) collection.Add(nameof(Attack2));
            if ((mask & (1 << Attack3)) == (1 << Attack3)) collection.Add(nameof(Attack3));
        }
    }
}
