//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemserk.Examples
{
    
    
    public partial class Damages
    {
        
        public static int Melee = 1 << 1;
        
        public static int Ranged = 1 << 0;
        
        public static int Thorn = 1 << 2;
        
        public static int Poison = 1 << 3;
        
        public static string ValueToName(int value)
        {
            if (value == Melee) return nameof(Melee);
            if (value == Ranged) return nameof(Ranged);
            if (value == Thorn) return nameof(Thorn);
            if (value == Poison) return nameof(Poison);
            return null;
        }
        
        public static void GetNames(int mask, System.Collections.Generic.ICollection<string> collection)
        {
            if ((mask & Melee) == Melee) collection.Add(nameof(Melee));
            if ((mask & Ranged) == Ranged) collection.Add(nameof(Ranged));
            if ((mask & Thorn) == Thorn) collection.Add(nameof(Thorn));
            if ((mask & Poison) == Poison) collection.Add(nameof(Poison));
        }
    }
}
