//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemserk.Examples
{
    
    
    public class DamageTypes
    {
        
        public static int Fire = 1 << 0;
        
        public static int Ice = 1 << 1;
        
        public static int Cold = 1 << 2;
        
        public static int Lightning = 1 << 3;
        
        public static int Shocking = 1 << 4;
        
        public static int Electric = 1 << 5;
        
        public static int BaseDamages = Fire | Ice | Lightning;
        
        public static int IceDamages = Ice | Cold | Lightning;
        
        public static int ElectricDamages = Shocking | Electric;
        
        public static bool MatchAny(int a, int b)
        {
            return (a & b) != 0;
        }
    }
}
